# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cc5e52e6-06a9-4677-876f-b95e0be1d8be";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/cc5e52e6-06a9-4677-876f-b95e0be1d8be";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/49AA-BD77";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/srv" = {
    # device = "/dev/md127";
    device = "UUID=3f2f16ce-f0a4-4b24-8606-dea5614c65f6";
    fsType = "ext4";
    enable = true;
    depends = ["/srv"];
    mountPoint = "/srv";
    options = [
      "defaults"
      "nofail"
    ];
    neededForBoot = false;
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f618c633-e77f-4537-aa08-fe8d3da0e3c2";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.swraid.enable = true;
}
