certs:
	mkcert --install -cert-file /etc/node-red/node-red.containers+1.pem -key-file /etc/node-red/node-red.containers+1-key.pem node-red.containers node-red.local
	chown node-red:services /etc/node-red/node-red.containers+1*